// Blog articles: { slug, title, description, date, readMins, tool:{name,url}, body (trusted HTML) }.
module.exports = [
  {
    slug: "convert-text-to-pdf-on-mobile",
    title: "Convert Text to PDF on Mobile",
    description:
      "Turn notes, essays or office text into a clean PDF right from your phone browser — free, private and without installing any app.",
    date: "2026-09-28",
    readMins: 6,
    tool: { name: "Text to PDF", url: "/tools/text-to-pdf" },
    body: "<p>Need to submit an assignment, share meeting notes, or send an official letter from your phone? Converting text to PDF on mobile used to mean installing a heavy app, creating an account, and hoping your document does not end up on a strange server. There is a better way: a free browser-based <a href='/tools/text-to-pdf'>Text to PDF converter</a> that works on any phone in seconds.</p><h2>Why PDF is the right format for sharing text</h2><p>Plain text files and phone notes look different on every device — fonts shift, line breaks move, and formatting disappears. A PDF freezes your layout exactly as you designed it, so your CV, application or notice looks professional on the recipient's screen, whether they open it on a phone, tablet or office computer. PDFs are also harder to edit accidentally, which matters for official documents.</p><h2>Method: convert in your mobile browser</h2><p>The fastest approach needs no installation at all:</p><ol><li>Open the <a href='/tools/text-to-pdf'>Text to PDF tool</a> in Chrome or Safari on your phone.</li><li>Paste your text (or type directly) into the editor box.</li><li>Choose a page size — A4 for official documents — and press <strong>Download PDF</strong>.</li><li>Your file saves straight to your Downloads folder, ready to share on WhatsApp, email or Google Drive.</li></ol><p>Because processing happens locally in your browser, even long documents convert instantly and your text is never uploaded anywhere.</p><h2>Tips for a professional-looking PDF</h2><p>Keep paragraphs short and use clear headings so the document scans well on small screens. If your text comes from a chat app, remove extra blank lines first — they create empty pages. For Arabic or Urdu text, check that the script renders correctly in the preview before downloading. And always open the downloaded PDF once to confirm page breaks fall in sensible places.</p><h2>What about Word documents?</h2><p>If your starting point is a .docx file rather than plain text, use our <a href='/tools/word-to-pdf'>Word to PDF converter</a> instead — it extracts your document's text and rebuilds it as a clean PDF. Going the other direction? The <a href='/tools/pdf-to-word'>PDF to Word tool</a> pulls editable text out of a PDF. Together with <a href='/tools/jpg-to-pdf'>JPG to PDF</a> for scanned pages, you have a complete mobile document kit with nothing to install.</p>",
  },
  {
    slug: "best-practices-image-compression",
    title: "Image Compression Best Practices",
    description:
      "Compress photos for job portals, WhatsApp and websites without visible quality loss — sizes, formats and settings explained.",
    date: "2026-09-21",
    readMins: 7,
    tool: { name: "Image Compressor", url: "/tools/image-compressor" },
    body: "<p>A 6 MB phone photo will not upload to a job portal, eats mobile data on WhatsApp, and slows any website it sits on. Image compression solves this — but done badly, it turns photos into blurry blocks. Here are the practices that keep files small <em>and</em> sharp.</p><h2>1. Know your target size first</h2><p>Different destinations need different sizes. Job portals and government forms usually ask for 20 KB–200 KB per photo. WhatsApp compresses automatically, but sending a pre-compressed 300–500 KB image arrives noticeably sharper. Website banners should stay under 200 KB for fast loading. Start from the requirement, not from a random quality slider.</p><h2>2. Choose quality 70–80 for photos</h2><p>For JPEG photographs, quality 70–80% is the sweet spot: files shrink to roughly a tenth of the original with differences invisible at normal viewing sizes. Drop below 60% only for thumbnails. Our free <a href='/tools/image-compressor'>Image Compressor</a> lets you preview the result and file size before downloading, so you can find your own balance in seconds.</p><h2>3. Resize dimensions before compressing</h2><p>A 4000-pixel-wide photo displayed at 800 pixels wastes most of its bytes. Shrink dimensions first with an <a href='/tools/image-resizer'>Image Resizer</a>, <em>then</em> compress — the combination beats either step alone. As a rule, never upload more pixels than the screen or form will actually show.</p><h2>4. Pick the right format</h2><p>JPEG for photographs, PNG for screenshots, logos and anything with text or transparency. Converting a photo to PNG balloons the size; converting a logo to JPEG blurs its edges. Match format to content and you win half the battle before touching any slider.</p><h2>5. Keep an original, always</h2><p>Compression discards data permanently — you cannot restore quality later. Keep the original photo backed up and compress copies for sharing. Our compressor runs entirely in your browser, so your originals never leave your device while you experiment freely.</p><h2>Quick workflow that works</h2><p>Upload, set quality to 75%, check the size, resize dimensions if still too big, download. Two minutes, professional results — and if the file must become part of a document, convert it straight to PDF with <a href='/tools/jpg-to-pdf'>JPG to PDF</a>.</p>",
  },
  {
    slug: "crop-images-without-quality-loss",
    title: "Crop Images Without Quality Loss",
    description:
      "Crop passport photos, profile pictures and documents cleanly — why cropping never reduces quality and the mistakes to avoid.",
    date: "2026-09-14",
    readMins: 6,
    tool: { name: "Image Crop", url: "/tools/image-crop" },
    body: "<p>Good news first: cropping itself never reduces image quality. It simply discards the pixels outside your selection — the pixels you keep stay exactly as sharp as the original. Quality loss after cropping almost always comes from something else: saving in the wrong format, or stretching the cropped result back up. Here is how to crop cleanly every time.</p><h2>Step 1: Start from the highest-resolution original</h2><p>Always crop the original photo, not a copy that WhatsApp or Facebook already compressed. Each re-save of a JPEG loses a little detail, so one crop from the original beats a chain of edits. Keep the original file safe and work on a copy.</p><h2>Step 2: Lock the right aspect ratio</h2><p>Most destinations expect a fixed shape: 1:1 square for profile pictures, 3:4 or 35×45 mm proportions for passport and visa photos, 16:9 for banners. Our <a href='/tools/image-crop'>Image Crop tool</a> offers preset ratios so you do not have to measure pixels yourself — pick the preset, position the box, done.</p><h2>Step 3: Crop tight, but not tighter than needed</h2><p>Leave a small margin around faces and text. Over-cropping forces you to upscale later, and upscaling is what actually destroys sharpness. If the cropped image ends up smaller than required, go back to a larger selection rather than stretching pixels.</p><h2>Step 4: Export in the correct format</h2><p>Save photographs as JPEG at 85–90% quality and graphics or documents as PNG. This single choice matters more than any other setting. If the cropped photo must be uploaded to a portal with a size cap, run it through our <a href='/tools/image-compressor'>Image Compressor</a> afterwards — cropping first means the compressor has fewer pixels to process and finishes faster.</p><h2>Common mistakes to avoid</h2><p>Screenshotting instead of cropping (screenshots capture screen resolution, not photo resolution), cropping an already-compressed forward, and ignoring the destination's required dimensions. Check the required size <em>before</em> you crop: if a portal wants 800×600 and your crop is 400×300, you will be forced to upscale. Measure twice, crop once.</p>",
  },
  {
    slug: "merge-pdf-files-online-free",
    title: "Merge PDF Files Online Free",
    description:
      "Combine your CV, certificates, passport and photos into one PDF for job and visa applications — in the right order, without software.",
    date: "2026-09-07",
    readMins: 6,
    tool: { name: "PDF Merge", url: "/tools/pdf-merge" },
    body: "<p>UAE job portals, visa applications and university admissions almost always ask for <strong>one</strong> PDF — but your documents live in five separate files: CV, degree, passport copy, photo, experience letter. Merging them correctly is a small task with an outsized impact on whether your application looks professional.</p><h2>Why order matters</h2><p>Recruiters and visa officers open dozens of files daily. Put documents in the order the listing asks for (usually: application form, CV, certificates, passport, photo). A single well-ordered file signals care; five attachments in random order signal chaos. Name the merged file clearly, e.g. <code>Ahmed-Khan-Application.pdf</code>, never <code>merged-final-2.pdf</code>.</p><h2>Merge in your browser in 4 steps</h2><ol><li>Open our free <a href='/tools/pdf-merge'>PDF Merge tool</a> on any device.</li><li>Upload your PDFs <strong>in the order you want them</strong> — first uploaded becomes the first pages.</li><li>Press merge and wait a few seconds (everything runs locally, so even large files are quick).</li><li>Download the combined file and open it once to confirm the page order.</li></ol><h2>Before merging: prepare each file</h2><p>Convert photos and scans to PDF first with <a href='/tools/jpg-to-pdf'>JPG to PDF</a> or <a href='/tools/png-to-pdf'>PNG to PDF</a>, and turn Word documents into PDF with <a href='/tools/word-to-pdf'>Word to PDF</a>. Consistent page sizes (A4) make the merged result look tidy. If the portal has a file-size limit, finish with <a href='/tools/pdf-compress'>PDF Compress</a> to squeeze under the cap.</p><h2>Privacy note for sensitive documents</h2><p>Passports and certificates are sensitive. Our merger processes files locally in your browser — your documents are never uploaded to a server, which is exactly what you want for identity documents. Be wary of any free tool that requires uploading your passport to an unknown server.</p>",
  },
  {
    slug: "uae-vat-calculator-guide",
    title: "UAE VAT Guide: How 5% VAT Works",
    description:
      "Understand the UAE's 5% VAT: add or remove VAT from any price, see real invoice examples, and know what is exempt.",
    date: "2026-08-30",
    readMins: 7,
    tool: { name: "VAT Calculator", url: "/tools/vat-calculator" },
    body: "<p>The UAE applies 5% Value Added Tax on most goods and services — one of the lowest rates in the world, but still a source of daily confusion. Is that restaurant bill VAT-inclusive? How much VAT sits inside a AED 1,050 invoice? This guide answers with numbers, not jargon.</p><h2>The two directions: adding and removing VAT</h2><p><strong>Adding VAT:</strong> multiply the base price by 1.05. A AED 200 service becomes AED 210, of which AED 10 is VAT. <strong>Removing VAT</strong> (extracting it from a VAT-inclusive price): divide by 1.05. A AED 1,050 invoice contains AED 1,000 base + AED 50 VAT — <em>not</em> AED 997.50, the common mistake of subtracting 5%. Our <a href='/tools/vat-calculator'>UAE VAT Calculator</a> does both directions instantly so you never do long division at a checkout counter again.</p><h2>Real examples</h2><ul><li>Freelancer quotes AED 5,000 + VAT → client pays AED 5,250.</li><li>Shop receipt shows AED 105 total (inclusive) → VAT inside is AED 5.</li><li>Annual rent AED 60,000 for a commercial unit + VAT → AED 63,000 total.</li></ul><h2>What is zero-rated or exempt?</h2><p>Some categories — certain healthcare, education, residential rent, and exports — are zero-rated or exempt, meaning no 5% is added. Rules have fine print (e.g. commercial vs residential property), so for business decisions confirm with the Federal Tax Authority guidance or your accountant. This calculator handles the arithmetic; it is not tax advice.</p><h2>VAT and currency together</h2><p>Buying from abroad? Convert the foreign price with our <a href='/tools/currency-converter'>Currency Converter</a> first, then apply 5% VAT on the AED figure. And if you invoice internationally, pairing the VAT math with a <a href='/tools/word-to-pdf'>Word to PDF</a> invoice keeps your paperwork clean and professional.</p>",
  },
  {
    slug: "find-qibla-direction-mobile",
    title: "Find Qibla Direction on Your Phone",
    description:
      "Find the accurate prayer direction using your phone's GPS and compass — how Qibla calculation works and how to verify it.",
    date: "2026-08-22",
    readMins: 6,
    tool: { name: "Qibla Finder", url: "/tools/qibla-finder" },
    body: "<p>Travel, a new office, or a hotel room — sooner or later every Muslim needs the prayer direction in an unfamiliar place. Your phone already carries everything required: GPS for your position and a compass for orientation. Here is how to get an accurate Qibla in under a minute.</p><h2>How Qibla direction is calculated</h2><p>The Qibla is the great-circle bearing from your location to the Kaaba in Makkah (21.4225° N, 39.8262° E). It is pure mathematics: given your GPS coordinates, one formula gives the exact angle. No estimates, no asking around. Our <a href='/tools/qibla-finder'>Qibla Finder</a> runs this calculation the moment your browser shares your location.</p><h2>The 60-second phone method</h2><ol><li>Open the <a href='/tools/qibla-finder'>Qibla Finder</a> and allow location access when asked.</li><li>Hold your phone flat and let the compass settle for a few seconds.</li><li>Rotate until the indicator points to the Kaaba bearing shown (e.g. 258° in the UAE).</li><li>Lay your prayer mat along that line.</li></ol><h2>Accuracy tips that actually matter</h2><p><strong>Calibrate the compass:</strong> wave the phone in a figure-eight motion if the needle jumps. <strong>Avoid metal:</strong> stand away from fridges, cars and reinforced walls, which distort magnetic sensors. <strong>Cross-check:</strong> compare with the sun's position or a second device when precision matters. In the UAE the Qibla points roughly west-southwest — if your reading says north, recalibrate.</p><h2>Pair it with prayer times</h2><p>Direction is half the equation; timing is the other half. Check today's schedule on our <a href='/#prayer'>UAE Prayer Times</a> widget, which counts down to the next prayer and adapts to Sharjah, Dubai, Abu Dhabi and Ajman. Direction plus timing, both free, both in your pocket.</p>",
  },
  {
    slug: "send-money-home-exchange-rates",
    title: "Sending Money Home: Exchange Rates",
    description:
      "AED to PKR, INR and PHP explained: mid-market vs counter rates, timing transfers, and converting like a pro before you remit.",
    date: "2026-08-15",
    readMins: 7,
    tool: { name: "Currency Converter", url: "/tools/currency-converter" },
    body: "<p>Every month, millions of UAE residents convert dirhams into rupees, pesos and takas. A rate difference of half a percent sounds tiny — until it repeats twelve times a year on AED 3,000 transfers. Understanding exchange rates is the highest-paid five minutes of your month.</p><h2>Mid-market rate vs the rate you get</h2><p>Google and our <a href='/tools/currency-converter'>Currency Converter</a> show the <strong>mid-market rate</strong> — the midpoint between buy and sell prices, the fairest possible benchmark. Exchange houses and apps add a margin on top (plus sometimes a flat fee). The gap between the mid-market rate and your offered rate is the true cost of your transfer. Always compare offers against the live mid-market figure first.</p><h2>A worked example: AED to PKR</h2><p>Suppose the live rate is 1 AED = 75.47 PKR. Sending AED 2,000 at mid-market would mean about PKR 150,947. If an exchange house offers 74.90, you receive PKR 149,800 — a difference of over a thousand rupees on one transfer. Checking the <a href='/tools/currency-converter'>live converter</a> before walking to the counter turns a guess into a negotiation.</p><h2>Three habits that save real money</h2><ul><li><strong>Check before you go.</strong> Rates move daily; a 30-second check sets your expectation and exposes bad offers instantly.</li><li><strong>Compare total cost, not just rate.</strong> A slightly worse rate with zero fee can beat a great rate with a AED 25 fee on small amounts.</li><li><strong>Avoid airport counters for big sums.</strong> Convenience margins at airports are consistently the worst — plan ahead.</li></ul><h2>Remember the peg</h2><p>The dirham is pegged at 3.6725 per US dollar, so USD transfers are stable — but PKR, INR and PHP float, which is where vigilance pays. Bookmark the converter, check the Hijri and Gregorian date context on our <a href='/#today'>UAE Today dashboard</a>, and remit with confidence instead of hope.</p>",
  },
];
