// Image + calculator + utility tool pages data (8). Same schema as tools1.js.
module.exports = [
  {
    slug: "image-compressor", name: "Image Compressor",
    title: "Compress Images Online Free",
    description: "Reduce image size free without visible quality loss. Perfect for job portals and WhatsApp — private, in-browser.",
    h1: "Image Compressor",
    overview: [
      "Shrink photos to fit upload limits without turning them into mush. This free compressor reduces JPG and PNG file sizes dramatically while keeping them sharp at normal viewing sizes — tuned for job portals, visa forms, WhatsApp sharing and fast websites.",
      "Drag in a photo, pick a quality level, watch the live size preview, and download. Because compression runs on your device, originals stay private and batch work finishes in seconds.",
    ],
    understanding: [
      "JPEG compression works by discarding visual detail humans barely notice — at 70–80% quality, files shrink to roughly a tenth with no visible difference on phones and screens. The trick is stopping before artifacts appear: smooth skies and faces show damage first, which is why the live preview matters more than any fixed setting.",
      "PNG screenshots compress differently (lossless palette reduction). For photos use JPG output; for graphics with text keep PNG. Pair with Image Resizer first when dimensions also exceed requirements — fewer pixels compress further.",
    ],
    steps: [
      { t: "Upload your image", d: "Drop in a JPG or PNG photo. The original size is shown immediately." },
      { t: "Set quality", d: "Move the slider (75% is a great default) and watch the estimated size update live." },
      { t: "Preview", d: "Compare the compressed preview against the original at full zoom." },
      { t: "Download", d: "Save the smaller file — named clearly — and upload or share it." },
    ],
    features: [
      { t: "Huge savings", d: "Typical 70–90% size reduction on phone photos." },
      { t: "Live preview", d: "See size and quality before downloading." },
      { t: "Private", d: "Images never leave your device." },
      { t: "Portal-ready", d: "Dial exact sizes for 20 KB–200 KB form limits." },
      { t: "JPG + PNG", d: "Smart handling for photos and graphics." },
      { t: "Free unlimited", d: "Compress as many images as you need." },
    ],
    faqs: [
      { q: "What quality setting should I use?", a: "75–80% for photos heading to portals or WhatsApp; 85–90% when quality matters most (printing, portfolios). Below 60% only for tiny thumbnails." },
      { q: "Will compressed photos still print well?", a: "For standard 4×6 prints, a well-compressed 1–2 MB file prints beautifully. For large enlargements, keep the original untouched." },
      { q: "Are my photos uploaded?", a: "No — compression uses the Canvas API on your device. Your photos never cross the network." },
      { q: "Portal needs under 100 KB. Possible?", a: "Usually yes: resize dimensions down first with Image Resizer, then compress at 70%. Text-heavy scans may need lower dimensions to hit tiny caps." },
      { q: "JPG or PNG output?", a: "Photos: JPG. Screenshots, logos, text graphics: PNG. The tool picks sensibly based on your input." },
    ],
    tips: ["Compress copies, keep originals backed up — compression is one-way.", "Resize dimensions before compressing for the smallest files.", "Zoom the preview to 100% to judge real sharpness.", "For documents, convert the compressed image to PDF afterwards."],
    widget: { type: "image-compress" },
    related: ["image-resizer", "jpg-to-pdf"],
  },
  {
    slug: "image-resizer", name: "Image Resizer",
    title: "Resize Images Online Free",
    description: "Resize photos to exact pixel dimensions free. Lock aspect ratio, keep quality — in your browser, no signup.",
    h1: "Image Resizer",
    overview: [
      "Need exactly 800×600, or a photo that fits a portal's dimension rules? This resizer changes image dimensions precisely — with aspect-ratio locking so nothing stretches — while keeping the result sharp.",
      "Upload, type the width or height, preview, download. Like all our image tools, resizing happens on your device: fast, private and free.",
    ],
    understanding: [
      "Resizing (resampling) recalculates every pixel for the new dimensions using high-quality smoothing, so downscaling a 4000px photo to 800px keeps it crisp — you are discarding excess detail, not damaging what remains. Upscaling (enlarging) cannot invent detail, so results soften: always start from the largest original available.",
      "Locking aspect ratio prevents the classic stretched-face mistake: change width and height follows automatically. Export as JPG for photos, PNG for graphics — matching format to content, as with compression.",
      "Batch consistency matters when one application needs several images: resize every photo for the same submission to identical dimensions so the set looks deliberate rather than assembled. Portals that auto-generate previews also behave better with uniform sizes, and equally-sized images compress to predictable file sizes, making it easier to stay under byte caps without repeated trial and error.",
    ],
    steps: [
      { t: "Upload", d: "Select the photo. Its current dimensions are displayed." },
      { t: "Set new size", d: "Enter width or height (aspect lock keeps proportions), or pick a preset." },
      { t: "Preview", d: "Check the resized preview for sharpness and framing." },
      { t: "Download", d: "Save in JPG or PNG and use it wherever exact size matters." },
    ],
    features: [
      { t: "Exact pixels", d: "Type precise dimensions for portal requirements." },
      { t: "Aspect lock", d: "Proportions preserved — no stretching, ever." },
      { t: "Sharp downscale", d: "High-quality resampling keeps detail crisp." },
      { t: "Format choice", d: "Export JPG for photos, PNG for graphics." },
      { t: "Private", d: "All processing on-device." },
      { t: "Free", d: "No account, no limits." },
    ],
    faqs: [
      { q: "Will resizing reduce quality?", a: "Downscaling from a large original stays crisp. Upscaling beyond the original size softens — avoid enlarging more than ~1.5x for important images." },
      { q: "How do I keep proportions?", a: "Keep aspect-ratio lock on (it is on by default): enter either width or height and the other follows automatically." },
      { q: "What size do portals usually want?", a: "Common asks: 800×600 or under for uploads, file caps of 20–200 KB. Resize dimensions first, then compress to hit the byte cap." },
      { q: "JPG or PNG after resizing?", a: "Photos → JPG; screenshots/logos/text → PNG. The tool lets you choose at download." },
      { q: "Are uploads private?", a: "Yes — resizing runs on canvas in your browser; files never leave your device." },
    ],
    tips: ["Always resize from the largest original, never from a thumbnail.", "Check both dimensions AND file size against portal rules.", "For profile pictures, crop square first, then resize.", "Batch tip: resize all images for one application identically."],
    widget: { type: "image-resize" },
    related: ["image-compressor", "image-crop"],
  },
  {
    slug: "image-crop", name: "Image Crop",
    title: "Crop Images Online Free",
    description: "Crop photos to exact ratios free. Passport, visa and profile presets — precise, private, in-browser.",
    h1: "Image Crop Tool",
    overview: [
      "Cut out exactly what you need: a passport face, a square profile picture, a clean document scan. This cropper gives you preset ratios and pixel-precise control, with a live preview before you commit.",
      "Cropping discards unwanted pixels without touching the quality of what remains. Everything runs locally — your photos stay yours.",
    ],
    understanding: [
      "Cropping is lossless by nature: kept pixels are copied bit-for-bit, so sharpness is fully preserved. Quality problems blamed on cropping actually come from upscaling afterwards (stretching a small crop bigger) or re-saving as low-quality JPG — both avoidable with the workflow below.",
      "Presets encode common requirements (1:1 square, 3:4 portrait, 16:9 wide, 35×45 passport proportions) so you frame once and meet the spec. After cropping, resize and compress only if the destination demands smaller files.",
      "Framing deserves a second look before you commit: check that text near edges is fully inside the box, that faces have breathing room on all sides, and that background clutter is genuinely excluded rather than half-visible. A thirty-second review at full zoom catches tilted horizons, cut-off signatures and stray fingers — flaws that are trivial to fix before cropping but annoying to repair afterwards.",
    ],
    steps: [
      { t: "Upload photo", d: "Select the highest-resolution original available." },
      { t: "Choose ratio", d: "Pick a preset (square, passport, wide) or free crop." },
      { t: "Position the box", d: "Drag values to frame the subject with a small margin." },
      { t: "Crop and download", d: "Export as JPG or PNG and verify dimensions." },
    ],
    features: [
      { t: "Preset ratios", d: "Square, passport, ID and banner proportions built in." },
      { t: "Pixel precision", d: "Numeric controls for exact framing." },
      { t: "Lossless crop", d: "Kept pixels stay bit-for-bit identical." },
      { t: "Live preview", d: "See the result before downloading." },
      { t: "Private", d: "On-device processing only." },
      { t: "Free", d: "No signup, no watermark." },
    ],
    faqs: [
      { q: "Does cropping lower quality?", a: "No. Cropping only removes outer pixels; the remaining image is untouched. Quality drops only if you upscale the crop afterwards." },
      { q: "What ratio for passport photos?", a: "Most UAE and international applications want 35×45 mm proportions (roughly 3:4). Use the passport preset, keep the face centered with margin, and check the official photo rules too." },
      { q: "Can I crop screenshots?", a: "Yes — crop freely, and export as PNG to keep text sharp." },
      { q: "My crop is smaller than required. Help?", a: "Go back to a larger selection from the original rather than stretching. Upscaling softens detail permanently." },
      { q: "Are my photos uploaded?", a: "Never. Cropping runs on canvas locally in your browser." },
    ],
    tips: ["Crop the original, not a WhatsApp-forwarded copy.", "Leave margin around faces — portals reject edge-touching crops.", "Check required dimensions BEFORE cropping.", "After cropping, compress only if a file-size cap demands it."],
    widget: { type: "image-crop" },
    related: ["image-resizer", "image-compressor"],
  },
  {
    slug: "currency-converter", name: "Currency Converter",
    title: "Currency Converter - Live Rates",
    description: "Convert currencies at live mid-market rates free. AED to PKR, INR, USD and 30+ currencies with popular conversions.",
    h1: "Live Currency Converter",
    overview: [
      "How much is AED 1,000 in rupees today? This live converter answers in real time for 30+ currencies — AED, PKR, INR, USD, EUR, GBP, SAR, PHP and more — using fresh mid-market reference rates.",
      "Type an amount, pick both currencies, and the result updates as you type. A popular-conversions table shows 1, 100 and 1,000-unit values at a glance — perfect before visiting an exchange house or sending money home.",
    ],
    understanding: [
      "The converter fetches live reference (mid-market) rates — the fair midpoint between buy and sell prices. Exchange counters add their margin on top, so always compare their offer against this benchmark: the gap is your true transfer cost. Rates refresh automatically, and conversions compute instantly for any amount.",
      "The dirham is pegged at 3.6725 per US dollar, so USD pairs barely move — while PKR, INR and PHP float daily, which is exactly where checking first pays off. For the full story on remittance math, read our guide to sending money home.",
    ],
    steps: [
      { t: "Enter amount", d: "Type any value — 1000, for example — in the amount box." },
      { t: "Pick currencies", d: "Choose the source and target currencies (default AED to PKR)." },
      { t: "Read the result", d: "The converted figure and the live per-unit rate appear instantly." },
      { t: "Compare and act", d: "Use the mid-market figure to judge exchange-house offers before you commit." },
    ],
    features: [
      { t: "Live rates", d: "Fresh mid-market data, refreshed automatically." },
      { t: "30+ currencies", d: "All Gulf, South Asian and major world currencies." },
      { t: "Instant math", d: "Results update as you type, with swap button." },
      { t: "Popular table", d: "1 / 100 / 1000 quick-reference conversions." },
      { t: "Remittance-ready", d: "Built for AED→PKR/INR/PHP senders." },
      { t: "Free, no signup", d: "Check rates as often as you like." },
    ],
    faqs: [
      { q: "Is this the rate I will get at the exchange?", a: "Almost — this is the mid-market benchmark. Counters add a small margin, so expect a slightly lower figure. The benchmark tells you whether an offer is fair." },
      { q: "How often do rates update?", a: "Rates refresh automatically in the background. For exact transfer timing, recheck just before you transact." },
      { q: "Why is USD to AED always ~3.67?", a: "The dirham is officially pegged to the dollar at 3.6725, so that pair is stable by design. Other currencies float freely." },
      { q: "Can I convert any pair, like SAR to INR?", a: "Yes — pick any two of the 30+ supported currencies; conversion routes through live cross-rates automatically." },
      { q: "Is the converter free?", a: "Completely, with no account and no limits. Check rates every day if you like." },
    ],
    tips: ["Check the rate before leaving for the exchange counter.", "Compare total cost (rate + fees), not rate alone.", "Screenshot the live rate when negotiating large transfers.", "Read our remittance guide to understand margins."],
    widget: { type: "currency" },
    related: ["vat-calculator", "unit-converter"],
  },
  {
    slug: "vat-calculator", name: "VAT Calculator",
    title: "UAE VAT Calculator - 5% VAT",
    description: "Calculate UAE 5% VAT instantly: add VAT to net prices or extract it from gross. Free, with invoice examples.",
    h1: "UAE VAT Calculator (5%)",
    overview: [
      "The UAE's 5% VAT hides inside everyday prices — and extracting it trips up almost everyone. This calculator adds VAT to net amounts or pulls it out of VAT-inclusive totals in one click, with the base, VAT and total shown separately.",
      "Freelancers quoting clients, shoppers checking receipts, and small businesses raising invoices use it daily. Free, instant, and built for how VAT actually appears on Gulf paperwork.",
    ],
    understanding: [
      "Adding VAT is simple multiplication (×1.05), but removing it requires division (÷1.05) — subtracting 5% from a gross price gives the wrong answer. A AED 1,050 inclusive invoice holds AED 50 of VAT (1050 ÷ 1.05 = 1000 base), not AED 52.50. The calculator handles both directions so the classic mistake disappears.",
      "Remember this is arithmetic, not tax advice: zero-rated and exempt categories (some healthcare, education, residential rent) follow FTA rules with fine print. For accounting decisions, confirm with official guidance — then do the math here.",
      "Keep a paper trail for every figure you rely on: note the date, the gross or net starting amount, and which direction you calculated. Small businesses that log these three details per invoice reconcile their books dramatically faster at quarter-end, and the itemized base–VAT–total breakdown this tool shows maps directly onto standard UAE invoice line items.",
    ],
    steps: [
      { t: "Enter the amount", d: "Type the price as shown — net or gross." },
      { t: "Choose direction", d: "Select Add 5% VAT (net → gross) or Extract VAT (gross → base + VAT)." },
      { t: "Calculate", d: "Instantly see base amount, VAT portion and total, itemized." },
      { t: "Use the figures", d: "Copy numbers straight into quotes, invoices or expense claims." },
    ],
    features: [
      { t: "Both directions", d: "Add VAT or extract it — the two real-world needs." },
      { t: "Itemized output", d: "Base, VAT and total shown separately." },
      { t: "Correct math", d: "Proper ÷1.05 extraction, not the 5%-off error." },
      { t: "Invoice-ready", d: "Figures formatted for quotes and bills." },
      { t: "Instant + free", d: "No signup, results as you type." },
      { t: "Mobile first", d: "Settle a bill dispute at the table." },
    ],
    faqs: [
      { q: "How do I remove 5% VAT from AED 1,050?", a: "Divide by 1.05: base = AED 1,000, VAT = AED 50. Never just subtract 5% (that gives AED 997.50, which is wrong)." },
      { q: "What is the VAT rate in the UAE?", a: "5% standard rate on most goods and services since 2018, with specific zero-rated and exempt categories." },
      { q: "Is restaurant VAT included in menu prices?", a: "Usually yes — menus typically show VAT-inclusive prices. Use Extract mode on the bill total to see the VAT inside." },
      { q: "Can I use this for business invoices?", a: "For the arithmetic, absolutely. For tax compliance (registration, filing, exempt categories), follow Federal Tax Authority rules or consult an accountant." },
      { q: "Is the calculator free?", a: "Yes — unlimited calculations, no account needed." },
    ],
    tips: ["For quotes, always state whether prices include VAT.", "Extract VAT from receipts before claiming expenses.", "Pair with the currency converter for imports priced in USD.", "Round only the final total, never intermediate steps."],
    widget: { type: "vat" },
    related: ["currency-converter", "age-calculator"],
  },
  {
    slug: "age-calculator", name: "Age Calculator",
    title: "Age Calculator - Exact Age Online",
    description: "Calculate exact age from date of birth free. Years, months, days and total days — for forms, admissions and fun.",
    h1: "Age Calculator",
    overview: [
      "How old are you, exactly — in years, months and days? Enter a date of birth and get a precise age breakdown instantly, including total days lived and the next birthday countdown.",
      "Used for school admissions, visa forms, ID applications and job eligibility checks across the UAE — anywhere an exact age matters. Free, private, and accurate to the day.",
    ],
    understanding: [
      "Exact age is trickier than current-year minus birth-year: month lengths and leap years shift the answer. The calculator walks the calendar properly — borrowing months and days like long subtraction — so 29 February birthdays and year boundaries come out right.",
      "Many official forms ask for age “as on” a specific date (admission cutoffs, retirement rules). Pick any reference date, not just today, to answer those questions precisely.",
      "Save the result alongside the reference date whenever it matters: admission offices, HR departments and visa counters all interpret age relative to a cutoff, and a written record of “28 years, 4 months as on 31 March” prevents disputes that a bare birth year cannot settle. Recompute for each new cutoff rather than reusing old figures, since month boundaries shift the answer.",
    ],
    steps: [
      { t: "Enter date of birth", d: "Pick the birth date from the calendar control." },
      { t: "Choose reference date", d: "Leave today, or set a cutoff date for admissions and eligibility." },
      { t: "Calculate", d: "See years, months, days, total months, weeks and days lived." },
      { t: "Use it", d: "Copy the exact figure into your form or application." },
    ],
    features: [
      { t: "Exact breakdown", d: "Years, months, days — plus totals." },
      { t: "Any reference date", d: "Age as on admission cutoffs, not just today." },
      { t: "Leap-year correct", d: "29 Feb birthdays handled properly." },
      { t: "Birthday countdown", d: "Days until the next birthday." },
      { t: "Private", d: "Dates never leave your browser." },
      { t: "Free", d: "Unlimited calculations, no signup." },
    ],
    faqs: [
      { q: "How is exact age calculated?", a: "By calendar walking: full years first, then remaining months, then days — correctly handling 28/29/30/31-day months and leap years." },
      { q: "What about 29 February birthdays?", a: "Handled correctly: in non-leap years the anniversary lands per calendar rules, and day counts stay exact either way." },
      { q: "Can I check age on a past or future date?", a: "Yes. Set any reference date — useful for school admission cutoffs (e.g. age as on 31 March) or retirement eligibility." },
      { q: "Is my birth date stored?", a: "No. The calculation runs locally and nothing is sent or saved anywhere." },
      { q: "Why not just subtract the years?", a: "Because birthdays later in the year make simple subtraction off by one — and forms often need months and days too." },
    ],
    tips: ["For admissions, always compute age as on the official cutoff date.", "Double-check the birth certificate date before filling forms.", "Screenshot results for your records when applying online.", "Need it in another unit? Try the unit converter next."],
    widget: { type: "age" },
    related: ["unit-converter", "vat-calculator"],
  },
  {
    slug: "unit-converter", name: "Unit Converter",
    title: "Unit Converter - Convert Anything",
    description: "Convert units free: km to miles, kg to pounds, Celsius to Fahrenheit and more. Instant, accurate, no signup.",
    h1: "Unit Converter",
    overview: [
      "Miles or kilometers? Pounds or kilos? Celsius or Fahrenheit? This converter switches between everyday units instantly — for recipes, road trips, gym weights, weather and homework.",
      "Pick a category, enter a value, and see conversions across all units in that family at once. Precise factors, clean results, zero fuss.",
    ],
    understanding: [
      "Each category converts through a base unit: lengths through meters, weights through kilograms, temperatures through exact offset formulas (°F = °C × 9/5 + 32). Showing all units simultaneously beats one-pair-at-a-time tools when you are comparing, say, a UK recipe (grams) with a US one (cups are volume — use weight mode for dry goods).",
      "Watch significant figures: converting 5 ft 6 in to 167.64 cm is honest precision; quoting ten decimals from a rough input is false accuracy. The tool rounds sensibly for real-world use.",
      "When a result feeds a decision — medication doses, engineering clearances, luggage limits — convert twice using different paths as a sanity check. For example, convert kilograms to pounds directly, then cross-check via grams; matching answers confirm no input slip. This habit takes five seconds and catches the misplaced decimals that cause real-world mistakes.",
    ],
    steps: [
      { t: "Pick a category", d: "Length, weight, temperature, speed, area or data size." },
      { t: "Enter value", d: "Type the number in the unit you have." },
      { t: "Read all results", d: "Every unit in the family converts at once — no re-typing." },
      { t: "Copy and go", d: "Use the figure in your recipe, form or journey plan." },
    ],
    features: [
      { t: "6 categories", d: "Length, weight, temperature, speed, area, data." },
      { t: "All-units view", d: "One input, every conversion shown together." },
      { t: "Exact factors", d: "Defined constants, correct temperature offsets." },
      { t: "Sensible rounding", d: "Readable results, not false precision." },
      { t: "Instant", d: "Converts as you type." },
      { t: "Free", d: "No account, unlimited conversions." },
    ],
    faqs: [
      { q: "How many cm is 5 feet 6 inches?", a: "167.64 cm. Enter 5.5 feet in length mode (6 inches = half a foot) and read the centimeter result." },
      { q: "How do I convert Fahrenheit to Celsius?", a: "Select temperature, enter °F — the °C equivalent appears instantly, using the exact (°F − 32) × 5/9 formula." },
      { q: "Kg to pounds for gym weights?", a: "1 kg = 2.20462 lbs. Weight mode shows pounds, ounces and stones together — handy for UK/US programs." },
      { q: "Are conversions exact?", a: "Yes — standard defined factors (e.g. 1 inch = 2.54 cm exactly) and correct temperature formulas throughout." },
      { q: "Does it work offline?", a: "After the page loads, conversions run purely in JavaScript — no network needed per calculation." },
    ],
    tips: ["For recipes, weigh ingredients — volume cups vary by ingredient.", "Road signs: UAE uses km/h; UK uses mph — convert before driving abroad.", "Weather: 30°C = 86°F — temperature mode settles every debate.", "Data mode clarifies MB vs MiB when buying storage."],
    widget: { type: "unit" },
    related: ["age-calculator", "currency-converter"],
  },
  {
    slug: "qibla-finder", name: "Qibla Finder",
    title: "Qibla Finder - Prayer Direction",
    description: "Find the Qibla direction from anywhere free. GPS-based Kaaba bearing with live compass — private, no app needed.",
    h1: "Qibla Direction Finder",
    overview: [
      "In a new city, hotel or office? Point your phone at Makkah in under a minute. This finder uses your GPS location to compute the exact great-circle bearing to the Kaaba, then guides you with a live compass.",
      "No app install, no account — just allow location once. Free for travelers, new residents and anyone praying away from home.",
    ],
    understanding: [
      "The Qibla is the great-circle (shortest-path) bearing from your coordinates to the Kaaba at 21.4225° N, 39.8262° E. From the UAE it points west-southwest (~258°); from London it is southeast (~119°); from Jakarta it is northwest (~295°). Same math, different answer everywhere — which is why a calculator beats memory.",
      "Your phone contributes two sensors: GPS for position (accurate to meters outdoors) and the magnetometer compass for orientation. Calibrate by waving a figure-eight if the needle jumps, and step away from cars and steel structures that bend magnetic readings.",
    ],
    steps: [
      { t: "Allow location", d: "Open the tool and accept the location prompt — one tap." },
      { t: "Get your bearing", d: "Your Qibla angle appears (e.g. 193°), computed from live GPS." },
      { t: "Align the compass", d: "Hold the phone flat and rotate until the indicator centers." },
      { t: "Lay your mat", d: "Place your prayer mat along the shown line and pray." },
    ],
    features: [
      { t: "GPS-accurate", d: "Bearing computed from your real coordinates." },
      { t: "Live compass", d: "Visual guide rotates with your phone." },
      { t: "Works worldwide", d: "Any city on earth — travelers' essential." },
      { t: "Private location", d: "GPS stays in your browser; never stored." },
      { t: "No install", d: "Browser-based, works on any smartphone." },
      { t: "Free forever", d: "No account, no ads blocking the needle." },
    ],
    faqs: [
      { q: "Which direction is Qibla in Dubai?", a: "Approximately 258° (west-southwest). But use the tool for your exact spot — the bearing shifts slightly between emirates and buildings." },
      { q: "Do you store my location?", a: "No. Geolocation is read by your browser, used once for the calculation, and never transmitted to or stored by us." },
      { q: "The compass seems wrong. What now?", a: "Calibrate with a figure-eight motion, move away from metal and electronics, and hold the phone flat. Compare against a second device if precision is critical." },
      { q: "Does it work without internet?", a: "You need signal for the page and GPS fix; the math itself runs on-device. Download nothing — just keep location services on." },
      { q: "Can I also get prayer times?", a: "Yes — our UAE Prayer Times widget shows today's schedule with a countdown to the next prayer for Sharjah, Dubai, Abu Dhabi and Ajman." },
    ],
    tips: ["Calibrate the compass every new location for a steady needle.", "Avoid cars, lifts and steel furniture while measuring.", "Cross-check with the sun when possible (afternoon sun is west).", "Pair with prayer times so direction and timing are both covered."],
    widget: { type: "qibla" },
    related: ["currency-converter", "unit-converter"],
  },
];
