// PDF tool pages data (9). Fields: slug,name,title,description,h1,overview[],understanding[],steps[],features[],faqs[],tips[],widget,related[].
module.exports = [
  {
    slug: "jpg-to-pdf", name: "JPG to PDF",
    title: "Free JPG to PDF Converter Online",
    description: "Convert JPG images to PDF online free. Photos become a clean A4 PDF in your browser — no upload, no watermark, no signup.",
    h1: "JPG to PDF Converter",
    overview: [
      "Turn your photos into a professional PDF in seconds. Whether it is a scanned document, a photo of a receipt, or pictures for a job application, this free JPG to PDF converter combines your images into one clean, shareable file — directly in your browser.",
      "Unlike most converters, nothing is uploaded to a server. Your photos stay on your device, the conversion is instant even on mobile data, and the resulting PDF carries no watermark. Perfect for visa applications, job portals, school submissions and office paperwork across the UAE and beyond.",
    ],
    understanding: [
      "A PDF wraps each photo on its own page at a fixed size (A4 by default), so the recipient sees exactly what you see — no sideways images, no tiny thumbnails lost in a chat thread. The converter reads each JPG, scales it to fit the page while preserving proportions, and embeds it at full available quality.",
      "Order matters: the first image you upload becomes page one. For multi-page documents like passport copies or certificates, upload in reading order. If your pages are a mix of JPG and PNG, convert PNGs with our PNG to PDF tool first, or merge everything afterwards with PDF Merge.",
    ],
    steps: [
      { t: "Upload your images", d: "Tap the upload area and select one or more JPG photos from your phone, tablet or computer. You can add pages one by one." },
      { t: "Check the order", d: "Thumbnails appear in page order. Remove any wrong photo and re-add it at the end, or re-upload in the correct sequence." },
      { t: "Convert", d: "Press Convert to PDF. Each image is placed on its own A4 page, scaled to fit without distortion." },
      { t: "Download and share", d: "Save the PDF and share it on WhatsApp, email or upload it to the portal. Open it once to confirm the order." },
    ],
    features: [
      { t: "100% private", d: "Files never leave your device — conversion runs locally in your browser." },
      { t: "No watermark", d: "Your PDF is clean and professional, ready for official use." },
      { t: "Multi-page support", d: "Combine many photos into a single PDF in the order you choose." },
      { t: "Mobile friendly", d: "Works in any modern phone browser with nothing to install." },
      { t: "Full quality", d: "Images are embedded at high quality, scaled proportionally to A4." },
      { t: "Free forever", d: "No accounts, no subscriptions, no daily conversion limits." },
    ],
    faqs: [
      { q: "Is this JPG to PDF converter really free?", a: "Yes. There are no accounts, no trial limits and no watermarks. The tool runs entirely in your browser, so it costs us almost nothing to offer — and costs you nothing to use." },
      { q: "Are my photos uploaded to your servers?", a: "No. The conversion happens locally on your device using JavaScript. Your photos never travel over the network, which is why the tool also works fast on slow connections." },
      { q: "How many images can I convert at once?", a: "You can combine many images into one PDF. For very large batches (50+ high-resolution photos), convert in smaller groups to keep your phone browser responsive." },
      { q: "Will the PDF work for job and visa applications?", a: "Yes — the output is a standard PDF that opens in any reader. For official submissions, check the portal's file-size limit first; if needed, shrink photos with our Image Compressor before converting." },
      { q: "Can I convert PNG images too?", a: "This page is optimized for JPG. For PNG screenshots or graphics, use our PNG to PDF converter, which handles transparency correctly." },
    ],
    tips: ["Shoot documents straight from above in good light for sharp pages.", "Name the PDF clearly, e.g. Ahmed-Passport.pdf, before uploading anywhere.", "Check page order once after downloading — portals rarely let you re-order.", "Under a size limit? Compress images first, then convert."],
    widget: { type: "images-to-pdf", accept: "image/jpeg,.jpg,.jpeg", formats: "JPG / JPEG", lib: "jspdf" },
    related: ["png-to-pdf", "pdf-merge"],
  },
  {
    slug: "png-to-pdf", name: "PNG to PDF",
    title: "Free PNG to PDF Converter Online",
    description: "Convert PNG screenshots and graphics to PDF free. Transparency handled correctly, processed locally in your browser.",
    h1: "PNG to PDF Converter",
    overview: [
      "Screenshots, designs, receipts and graphics saved as PNG need a different touch than photos: transparency, sharp text edges and exact colors. This free PNG to PDF converter places each image on a clean page while preserving crisp detail — ideal for portfolios, evidence files and documentation.",
      "Everything runs in your browser, so screenshots of chats, payments or bookings never pass through a server. No signup, no watermark, and the output opens everywhere PDFs open.",
    ],
    understanding: [
      "PNG is a lossless format, which makes it perfect for anything containing text, lines or flat colors — but many portals only accept PDF. The converter flattens each PNG onto a white A4 page (transparent areas become white, exactly as a printer would render them) and scales proportionally so nothing stretches.",
      "For photographs, JPG to PDF usually gives smaller files; for screenshots and graphics, PNG to PDF keeps text razor-sharp. Mixing both? Convert each type with its dedicated tool, then join the results with PDF Merge.",
    ],
    steps: [
      { t: "Upload PNG files", d: "Select one or more PNG screenshots or graphics from your device using the upload area." },
      { t: "Arrange pages", d: "Files become pages in upload order — upload them in the sequence you want to present." },
      { t: "Convert to PDF", d: "One click places every image on its own page, flattened cleanly onto white." },
      { t: "Download and use", d: "Save the PDF for printing, emailing or uploading to any portal that requires PDF." },
    ],
    features: [
      { t: "Transparency-safe", d: "Transparent areas render as clean white, like a real printout." },
      { t: "Sharp text", d: "Lossless PNG detail preserved — screenshots stay readable." },
      { t: "Private by design", d: "Local browser processing; screenshots never uploaded." },
      { t: "Multi-page PDFs", d: "Combine many captures into one documented file." },
      { t: "Any device", d: "Phone, tablet or desktop — just a modern browser." },
      { t: "No signup", d: "Free with no account and no hidden limits." },
    ],
    faqs: [
      { q: "What happens to transparent backgrounds?", a: "They are flattened onto white, the same way a printer handles transparency. Your content stays exactly where it was, on a clean page." },
      { q: "Is my screenshot data private?", a: "Completely. Screenshots often contain personal chats or payment details — that is precisely why this tool processes everything locally and uploads nothing." },
      { q: "PNG or JPG for my document?", a: "Screenshots, scans of text and graphics: PNG. Camera photos: JPG. This page handles PNG; photos go through JPG to PDF for smaller files." },
      { q: "Can I merge the result with other PDFs?", a: "Yes. Download the PDF, then combine it with certificates or forms using our PDF Merge tool." },
      { q: "Why is my PDF bigger than expected?", a: "PNG is lossless, so detailed screenshots carry more data. If a portal caps file size, compress the PNG first or convert photos to JPG instead." },
    ],
    tips: ["Capture screenshots at full brightness for maximum text clarity.", "Crop status bars and clutter before converting for tidier pages.", "For long chat evidence, convert in chronological order.", "Need it smaller? Lower PNG dimensions before conversion, not after."],
    widget: { type: "images-to-pdf", accept: "image/png,.png", formats: "PNG", lib: "jspdf" },
    related: ["jpg-to-pdf", "pdf-merge"],
  },
  {
    slug: "text-to-pdf", name: "Text to PDF",
    title: "Free Text to PDF Converter Online",
    description: "Convert plain text to a clean PDF online free. Paste notes, letters or essays and download an A4 PDF instantly.",
    h1: "Text to PDF Converter",
    overview: [
      "Have words but need a document? Paste any text — notes, an application letter, homework, a notice — and get a properly paginated A4 PDF in one click. No word processor, no formatting battles, no app install.",
      "The tool wraps your text into clean pages with readable margins, entirely in your browser. Students, job seekers and office staff use it daily for quick, professional-looking documents.",
    ],
    understanding: [
      "Plain text has no pages, fonts or margins — a PDF gives it all three. The converter flows your text into A4 pages with comfortable line spacing, breaking pages at sensible points so paragraphs are never split awkwardly. Because it runs locally, even very long documents convert instantly.",
      "For styled Word documents with bold, tables or images, use Word to PDF instead — it preserves your formatting. For scanned pages you cannot select, JPG to PDF turns photos of paper into PDF pages.",
    ],
    steps: [
      { t: "Paste or type text", d: "Put your content in the editor box — paste from notes, WhatsApp or any app, or type directly." },
      { t: "Tidy it up", d: "Remove extra blank lines and check headings so the document reads cleanly." },
      { t: "Generate PDF", d: "Press Download PDF. Your text is laid out onto A4 pages automatically." },
      { t: "Share", d: "Save the file and send it by email, WhatsApp or upload — it looks the same everywhere." },
    ],
    features: [
      { t: "Instant conversion", d: "From paste to PDF in a single click, even for long texts." },
      { t: "Clean A4 layout", d: "Readable margins and sensible page breaks, automatically." },
      { t: "Fully private", d: "Your text never leaves the browser — safe for personal letters." },
      { t: "Mobile ready", d: "Convert notes straight from your phone, no app needed." },
      { t: "No formatting fuss", d: "No fonts to choose, no templates to fight — just clean output." },
      { t: "Free unlimited", d: "Convert as many documents as you like, forever free." },
    ],
    faqs: [
      { q: "Can I convert Urdu or Arabic text?", a: "Yes — paste RTL text and it converts like any other script. Always open the downloaded PDF once to confirm the script and line breaks look right." },
      { q: "Is there a length limit?", a: "No practical limit. Very long documents simply produce more pages; conversion still takes seconds because it all happens locally." },
      { q: "Will my text be stored anywhere?", a: "No. The text lives only in your browser tab and the PDF downloads to your device. Closing the tab removes everything." },
      { q: "Can I keep bold and headings?", a: "Plain text has no styling to keep. For formatted documents, use Word to PDF, which preserves headings, bold and structure." },
      { q: "What page size is used?", a: "Standard A4, the expected size for job applications, school work and official letters in the UAE and internationally." },
    ],
    tips: ["Add a title line at the top so the document looks intentional.", "Break long walls of text into short paragraphs before converting.", "Preview the PDF once — fix typos in the editor, not after.", "Need images too? Convert text first, then merge with photo PDFs."],
    widget: { type: "text-to-pdf", lib: "jspdf" },
    related: ["word-to-pdf", "pdf-merge"],
  },
  {
    slug: "pdf-to-jpg", name: "PDF to JPG",
    title: "Free PDF to JPG Converter Online",
    description: "Turn PDF pages into JPG images online free. Each page becomes a shareable photo — processed locally in your browser.",
    h1: "PDF to JPG Converter",
    overview: [
      "Need to share a PDF page on WhatsApp, post a certificate on social media, or attach a page where only images are accepted? This tool renders every page of your PDF into a crisp JPG image you can share anywhere.",
      "Conversion happens page by page in your browser at high resolution, so text stays readable and certificates stay sharp. No uploads, no watermarks, no waiting rooms.",
    ],
    understanding: [
      "A PDF page is vector-based — infinitely sharp — while a JPG is a fixed grid of pixels. The converter rasterizes each page at 2x scale (about 144 DPI equivalent and above), which keeps small text legible while keeping file sizes sensible for sharing. Each page downloads as its own image, numbered in order.",
      "For the reverse trip, JPG to PDF rebuilds a document from images. To pull editable text out of a PDF instead of images, use PDF to Word.",
    ],
    steps: [
      { t: "Upload your PDF", d: "Select the PDF file from your device. It loads locally — nothing is sent anywhere." },
      { t: "Convert pages", d: "Press Convert. Each page renders into a high-resolution JPG, shown as previews." },
      { t: "Download images", d: "Save all pages at once or pick individual ones — files are named in page order." },
      { t: "Share anywhere", d: "Send pages on WhatsApp, post them, or attach them wherever images are required." },
    ],
    features: [
      { t: "High resolution", d: "Pages render at 2x scale so small text stays readable." },
      { t: "Every page", d: "Full document conversion with previews before you download." },
      { t: "Private processing", d: "Your PDF never leaves your device." },
      { t: "Batch download", d: "Grab all pages as separate files in one go." },
      { t: "Works on mobile", d: "Convert documents straight from your phone browser." },
      { t: "Free, no signup", d: "Unlimited conversions without an account." },
    ],
    faqs: [
      { q: "What quality are the JPG images?", a: "Pages render at double scale (high resolution) and export at 92% JPEG quality — sharp enough to read fine print and re-print cleanly." },
      { q: "My PDF has 50 pages — will it work?", a: "Yes, though very large documents take longer and use more memory. For huge files, convert in ranges using PDF Split first." },
      { q: "Are password-protected PDFs supported?", a: "No — locked PDFs cannot be opened in the browser without the password. Unlock the file in your PDF reader first, then convert." },
      { q: "Can I get PNG instead of JPG?", a: "This tool outputs JPG, the best choice for sharing and small sizes. For document pages, JPG at high quality is sharper per kilobyte than PNG." },
      { q: "Is my document uploaded anywhere?", a: "Never. Rendering happens with PDF.js locally on your device — ideal for sensitive contracts and certificates." },
    ],
    tips: ["For WhatsApp sharing, one page per message reads better than collages.", "Keep page numbers in filenames so order survives re-sends.", "Need one page only? Convert, then download just that image.", "Printing later? Keep the original PDF — JPGs are for sharing, PDFs for print."],
    widget: { type: "pdf-to-images", lib: "pdfjs" },
    related: ["jpg-to-pdf", "pdf-split"],
  },
  {
    slug: "pdf-merge", name: "PDF Merge",
    title: "Merge PDF Files Online Free",
    description: "Merge multiple PDFs into one file free. Perfect for job and visa applications — private, local, no signup.",
    h1: "Merge PDF Files Online",
    overview: [
      "Application portals want one PDF; your life is scattered across five. This free merger combines CVs, certificates, passport copies and photos into a single well-ordered document in seconds.",
      "Files merge in the order you upload them, entirely on your device — so identity documents never touch a server. The result is a standard PDF accepted by every portal, embassy and employer.",
    ],
    understanding: [
      "Merging appends the page trees of each PDF into one file without re-rendering anything, so quality is preserved bit-for-bit: text stays selectable, and file size is roughly the sum of the inputs. That is why merging is instant even for large files.",
      "Prepare non-PDF inputs first: photos via JPG to PDF or PNG to PDF, Word files via Word to PDF. If the merged file exceeds a portal's size cap, run it through PDF Compress as a final step.",
    ],
    steps: [
      { t: "Upload PDFs in order", d: "Add your files in the sequence you want them to appear — first uploaded becomes the first pages." },
      { t: "Review the list", d: "Check filenames and order; remove mistakes before merging." },
      { t: "Merge", d: "One click combines everything into a single PDF in seconds." },
      { t: "Download and verify", d: "Open the result once to confirm order and completeness, then submit." },
    ],
    features: [
      { t: "Order control", d: "Pages follow your upload sequence exactly." },
      { t: "Zero quality loss", d: "Pages are combined, never re-rendered." },
      { t: "Private for ID docs", d: "Local processing — passports never uploaded." },
      { t: "Unlimited files", d: "Combine as many PDFs as your task needs." },
      { t: "Fast on mobile", d: "No uploads means no waiting on slow data." },
      { t: "Free forever", d: "No accounts, watermarks or page-count traps." },
    ],
    faqs: [
      { q: "Will merging reduce quality?", a: "No. Pages are copied exactly as they are — text remains selectable and images untouched. The output size is roughly the sum of the inputs." },
      { q: "Can I reorder pages after uploading?", a: "The tool merges in upload order, so upload in your desired sequence. For finer control, arrange with PDF Split first, then merge." },
      { q: "Is it safe for passports and certificates?", a: "Yes — merging happens locally in your browser, so sensitive documents never leave your device. Avoid online mergers that require uploading ID scans." },
      { q: "My merged file is too big for the portal. What now?", a: "Run it through PDF Compress, or compress source images before converting. Most portals accept 2–5 MB." },
      { q: "Can I merge PDFs with images and Word files?", a: "Convert them to PDF first (JPG to PDF, PNG to PDF, Word to PDF), then merge everything together here." },
    ],
    tips: ["Name the final file professionally: Name-Document-Type.pdf.", "Match the portal's requested document order exactly.", "Keep a copy of each source file before merging.", "Check the total page count — some portals cap pages, not just megabytes."],
    widget: { type: "pdf-merge", lib: "pdflib" },
    related: ["pdf-split", "pdf-compress"],
  },
  {
    slug: "pdf-split", name: "PDF Split",
    title: "Split PDF Online Free",
    description: "Split PDF pages free in your browser. Extract ranges or separate every page — private, fast, no signup.",
    h1: "Split PDF Pages",
    overview: [
      "Only need pages 3–5 of a 40-page document? Splitting extracts exactly the pages you want into a new, lightweight PDF — no printing, no screenshots, no quality loss.",
      "Choose a page range or burst every page into its own file. Like all our PDF tools, splitting runs locally, so confidential contracts and records stay on your device.",
    ],
    understanding: [
      "A PDF is a collection of independent pages, so extraction is surgically clean: chosen pages are copied into a fresh file with their fonts and images intact. The result is a genuine PDF (selectable text included), not a photo of one — which is why split files remain suitable for official use.",
      "Common flows: split out the signed page of a contract, separate a scanned batch into individual invoices, or pull your certificate out of a merged application file. Recombine selections later with PDF Merge.",
    ],
    steps: [
      { t: "Upload your PDF", d: "Select the file. It opens locally and the tool reads its page count." },
      { t: "Choose pages", d: "Enter a range like 3-5, pick single pages, or split every page into separate files." },
      { t: "Split", d: "The tool builds clean new PDFs containing only your chosen pages." },
      { t: "Download", d: "Save the extracted file — named clearly — and use it wherever needed." },
    ],
    features: [
      { t: "Ranges or burst", d: "Extract 3-5, cherry-pick pages, or separate all." },
      { t: "Original quality", d: "Pages copied exactly — text stays selectable." },
      { t: "Confidential-safe", d: "Local-only processing for sensitive files." },
      { t: "Instant", d: "No uploads, no queues — results in seconds." },
      { t: "Mobile capable", d: "Split documents from your phone browser." },
      { t: "Free unlimited", d: "No account, no page-count paywalls." },
    ],
    faqs: [
      { q: "Does splitting lower quality?", a: "Not at all. Pages are copied with all fonts and images intact — the output is a true PDF, identical in quality to the source pages." },
      { q: "How do I write a page range?", a: "Use formats like 1-3 for a span, or comma lists like 1,4,7 for individual pages. The tool validates your input before splitting." },
      { q: "Can I split a scanned PDF?", a: "Yes. Scanned pages split exactly like digital ones; the images inside are preserved at full resolution." },
      { q: "What about password-protected files?", a: "Locked PDFs must be unlocked in your reader first — browsers cannot open encrypted files without the password." },
      { q: "Can I rejoin split files later?", a: "Anytime. Our PDF Merge tool recombines split outputs in whatever order you choose." },
    ],
    tips: ["Note the source page numbers before splitting large files.", "Name outputs by content (Contract-Signed-Page.pdf), not split-1.pdf.", "Delete the oversized original from shared drives after extracting.", "Combine split + merge to reorder a document's pages."],
    widget: { type: "pdf-split", lib: "pdflib" },
    related: ["pdf-merge", "pdf-to-jpg"],
  },
  {
    slug: "pdf-compress", name: "PDF Compress",
    title: "Compress PDF Files Online Free",
    description: "Reduce PDF file size free to fit portal limits. Browser-based optimization that keeps documents readable.",
    h1: "Compress PDF Size",
    overview: [
      "Portal says max 2 MB, your file is 9 MB? Compression squeezes PDFs under upload limits while keeping every page readable — essential for job applications, visa files and email attachments.",
      "The tool re-saves your PDF with optimized object streams, stripping bloat that accumulates when files pass through scanners and editors. All local, all private, all free.",
    ],
    understanding: [
      "PDFs bloat for boring reasons: uncompressed object structures, embedded metadata, duplicated fonts, and full-resolution scans saved at print quality. Re-saving with compressed object streams and cleaned structure typically cuts 10–40% with zero visible change — the pages look pixel-identical because content streams are untouched.",
      "For dramatically oversized files, the real weight is usually scanned images. Best results come from compressing source images first, then converting and merging — use this tool as the final polish, not the only step.",
      "A useful habit is to check the document properties before and after: most PDF readers show file size and page count in the file details panel. If a single page carries the bulk of the weight — for example one full-page color scan among text pages — consider rebuilding just that page from a compressed image and merging it back. Targeted fixes like this beat blind global compression every time.",
    ],
    steps: [
      { t: "Upload your PDF", d: "Select the oversized file. It loads locally — nothing is transmitted." },
      { t: "Compress", d: "One click re-saves the file with optimized structure and compressed streams." },
      { t: "Check the result", d: "Compare old vs new size, and flip through pages to confirm readability." },
      { t: "Download", d: "Save the smaller file and upload it wherever the limit blocked you." },
    ],
    features: [
      { t: "Smaller files", d: "Typical savings of 10–40% on unoptimized PDFs." },
      { t: "Readable output", d: "Content untouched — pages look identical." },
      { t: "Private", d: "Your documents never leave the browser." },
      { t: "One click", d: "No settings to learn, no quality roulette." },
      { t: "Portal-ready", d: "Built to beat 1–5 MB upload caps." },
      { t: "Free", d: "No account, no per-file fees." },
    ],
    faqs: [
      { q: "How much smaller will my file get?", a: "It depends on the source: scanner-made PDFs often shrink 20–40%, while already-optimized exports may only drop a few percent. The tool always shows before/after sizes so you can judge." },
      { q: "Will text become blurry?", a: "No. This optimization restructures the file without touching page content — text and images render exactly as before." },
      { q: "My file is still too big. What next?", a: "The weight is likely full-page scans. Split the file, compress the pages as images, or rebuild from compressed sources with JPG to PDF and merge." },
      { q: "Is compression safe for official documents?", a: "Yes — pages are visually identical and text stays selectable. Always keep your original as backup, as with any file operation." },
      { q: "Are my documents uploaded?", a: "No. Compression runs entirely on your device, which also makes it fast on slow connections." },
    ],
    tips: ["Know the portal's exact MB limit before compressing.", "Keep originals — compress copies, not your only file.", "Image-heavy PDFs shrink most from compressed source images.", "After compressing, test-upload early instead of at the deadline."],
    widget: { type: "pdf-compress", lib: "pdflib" },
    related: ["pdf-merge", "image-compressor"],
  },
  {
    slug: "word-to-pdf", name: "Word to PDF",
    title: "Word to PDF Converter — DOCX to PDF Free",
    description: "Convert Word documents to PDF free online. Text and structure preserved, processed privately in your browser.",
    h1: "Word to PDF Converter",
    overview: [
      "Your CV looks perfect in Word — and falls apart on the recruiter's phone. Converting DOCX to PDF freezes your layout, fonts and structure exactly as intended, so applications and official letters always arrive looking right.",
      "Upload your .docx, get a clean PDF in seconds. Processing is local, so drafts and personal documents never leave your device — and there is no watermark stamped on your work.",
    ],
    understanding: [
      "Word files depend on installed fonts and app versions, which is why the same CV shifts on different computers. PDF embeds everything needed to render identically everywhere. The converter extracts your document's text and structure locally and rebuilds it as a fixed-layout PDF — headings, paragraphs and lists preserved in reading order.",
      "Complex elements (floating images, intricate tables, tracked changes) simplify in translation. For pixel-critical designs, print-to-PDF from Word itself; for everyday documents, this tool is faster and needs no Office installed.",
    ],
    steps: [
      { t: "Upload your Word file", d: "Select a .docx document. It is read locally in your browser." },
      { t: "Review extracted text", d: "The tool shows your document's content so you can confirm nothing is missing." },
      { t: "Convert", d: "One click rebuilds the content as a clean, paginated PDF." },
      { t: "Download and send", d: "Save the PDF and attach it — it will look identical for every recipient." },
    ],
    features: [
      { t: "Layout preserved", d: "Headings, paragraphs and lists keep their structure." },
      { t: "No Office needed", d: "Convert on any device, even without Word installed." },
      { t: "Private drafts", d: "CVs and letters never uploaded anywhere." },
      { t: "Professional output", d: "Clean pages with no watermark." },
      { t: "Fast", d: "Local extraction finishes in seconds." },
      { t: "Free unlimited", d: "Convert every version of your CV, free." },
    ],
    faqs: [
      { q: "Will my formatting survive?", a: "Text structure — headings, paragraphs, lists — is preserved. Elaborate floating layouts and embedded images are simplified, so check the PDF once before sending." },
      { q: "DOC or DOCX?", a: "Modern .docx files work best. For ancient .doc files, re-save as .docx in any free office app first." },
      { q: "Is my CV uploaded to a server?", a: "No. Extraction and PDF building happen locally — your employment history stays on your device." },
      { q: "Can I convert back later?", a: "Yes. Our PDF to Word tool extracts editable text from PDFs whenever you need to revise." },
      { q: "Why PDF for job applications?", a: "Recruiters open files on phones, tablets and office PCs. PDF is the only format guaranteed to look the same on all of them — and most UAE portals require it." },
    ],
    tips: ["Finalize spelling in Word before converting — fix, then convert.", "Use standard fonts (Arial, Calibri) for maximum compatibility.", "Keep the .docx as your editable master; PDF is the sending copy.", "Check page count — a 1-2 page CV reads best."],
    widget: { type: "word-to-pdf", lib: "mammoth+jspdf" },
    related: ["pdf-to-word", "pdf-merge"],
  },
  {
    slug: "pdf-to-word", name: "PDF to Word",
    title: "Free PDF to Word Converter",
    description: "Extract editable text from PDF to Word free. Get a .doc you can revise — private local processing, no signup.",
    h1: "PDF to Word Converter",
    overview: [
      "Stuck with a PDF you need to edit? This tool pulls the text out of your PDF and hands you a Word-compatible document you can revise, quote and reuse — no retyping, no expensive software.",
      "Extraction runs locally in your browser, so contracts, certificates and reports stay private. The output opens in Word, Google Docs and free office apps alike.",
    ],
    understanding: [
      "Most PDFs contain real text under the hood (unless scanned as images), and this tool recovers it page by page in reading order. The result is clean, editable content in a .doc file — formatting is simplified to keep the text faithful, which is the right trade for editing and quoting work.",
      "Scanned/image-only PDFs contain no text to extract — the output will be empty. For those, JPG to PDF style image handling or OCR software is needed instead. Going forward, keep masters in Word and send PDFs made with Word to PDF.",
    ],
    steps: [
      { t: "Upload your PDF", d: "Select the file. It is read locally; nothing is uploaded." },
      { t: "Extract text", d: "The tool reads every page and assembles the text in order." },
      { t: "Review", d: "Preview the extracted content to confirm completeness." },
      { t: "Download .doc", d: "Save the Word file and open it in Word or Google Docs to edit." },
    ],
    features: [
      { t: "Editable output", d: "Real text you can revise, not pictures of text." },
      { t: "Reading order", d: "Pages and paragraphs assembled sequentially." },
      { t: "Private", d: "Contracts stay on your device throughout." },
      { t: "Universal .doc", d: "Opens in Word, Docs, LibreOffice and more." },
      { t: "Fast", d: "Local extraction, results in seconds." },
      { t: "Free", d: "No account, no per-page charges." },
    ],
    faqs: [
      { q: "Will tables and images come along?", a: "Text extracts faithfully; complex tables and embedded images are simplified or skipped. For content reuse and editing, the text is what matters — and that comes through cleanly." },
      { q: "My PDF gives empty output. Why?", a: "It is likely a scanned image-only PDF with no embedded text. Such files need OCR (optical character recognition), which this lightweight tool does not include." },
      { q: "Is the output a real Word file?", a: "Yes — a Word-compatible .doc that opens for editing in Word, Google Docs and free alternatives." },
      { q: "Can I convert the edited file back to PDF?", a: "Absolutely — save as .docx and run it through our Word to PDF converter." },
      { q: "Are my documents private?", a: "Entirely. Extraction happens on your device; no document content is transmitted anywhere." },
    ],
    tips: ["For scanned pages, you need OCR — not text extraction.", "Clean up line breaks after extraction for smooth paragraphs.", "Attribute quoted sources properly when reusing extracted text.", "Save edited work as .docx to preserve your new formatting."],
    widget: { type: "pdf-to-word", lib: "pdfjs" },
    related: ["word-to-pdf", "pdf-split"],
  },
];
